apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-storage
  namespace: nfs-server-provisioner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: disk-redundant-fast
