apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: files
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.10.100
  share: /export
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - soft
  - intr
  - nodiratime
  - noatime
  - timeo=100
  - retrans=2
