apiVersion: v2
name: nfs-server-provisioner
description: Kubernetes External NFS Server Provisioner
maintainers:
  - name: Björn Kraus
    email: bjoern.kraus@phoenix-media.eu
    url: https://www.phoenix-media.eu

type: application
version: 0.1.1
appVersion: 0.1.3

dependencies:
  - name: csi-driver-nfs
    repository: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    version: v3.1.0
    condition: enabled
